### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [tvirtus/prj-rev-bwfs-dasmoto#1]
Great project, exceeded expectations.  HTML and CSS is well written and organized.  There wasn't any major repetition in your css which is a big plus.  

Since I really didn't have any critiques some suggestions for you to do in your future projects as they get larger and more complex.  Use comments for each section in html and have matching comments for those sections in your css.  

Second to prepare you for these upcoming projects I like you to go to flexboxfroggy.com, see how far you can get as the later project heavily use flexbox.

**Comment by tvirtus** [comment]
Thanks for great review and suggestions.
Any good links I could read up on commenting?
